### ISSUE TITLE
Inline edit for table view example missing from core

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#1050]
I created a demo page of inline edit for table view. Please review it and tell me your concerns blush @beanh66 @jgiardino @mcarrano 

**[Demo page](https://rawgit.com/dabeng/patternfly/ie-table-view-dist/dist/tests/inline-edit-for-table-view.html)**
[design doc](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#inline-edit-in-a-table-view)
[source code](https://github.com/dabeng/patternfly/commit/5c801ad129ae94d3b5f8e1c8f836453b0c1617aa)

**Comment by jgiardino** [comment]
Hi @dabeng, I'll let @beanh66 and @mcarrano comment on the design before making css/html comments, but I did want to make a comment on the icons you use.  

For the Save and Cancel icons, you're using icons from the [glyphicon set](https://getbootstrap.com/docs/3.3/components/#glyphicons), but there's a statement on our [patternfly icon page](http://www.patternfly.org/styles/icons/) that recommends against using these icons. @mcarrano is this still the case?

I realize you previously used these icons with the inline edit for forms, but I didn't realize this until it was merged (and I'm just now reading the text on our icon page, too).

**Comment by jgiardino** [comment]
Oh, one other question, should you open a PR to track discussion related to your updates?

**Comment by mcarrano** [comment]
@dabeng There are a couple of issues with the design for this. First, the column widths change when I switch into edit more. Is there a way to keep this from happening? Also, if you look at the design, the buttons are intended to be in a panel that extends down from the row rather than inline like you have them.

Regarding the question about glyphicons, I assume the statement on the Icons page is still valid. Perhaps @matthewcarleton can comment further on this.

There is a current implementation of this pattern in the React repo here: https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?&selectedKind=Table&selectedStory=Table%20With%20Inline%20Edit%20Row  We should try to be as consistent with this as possible. @jgiardino can any code from React be reused here or are the implementations just too different?

**Comment by dabeng** [comment]
@jgiardino  Thanks a lot for reminding. I just followed "btn-link" coding style - https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/buttons.html and used Glyphicons. I'll submit new patches to replace Bootstrap Glyphicons with PatternFly Icons.

**Comment by dabeng** [comment]
@mcarrano react version table view is just simple table. This inline edit demo page is based on table view derived from DataTables with pagination, filter and sort. It's a more complicated scenario. In short, keeping save&cancel buttons in the original row rather than in overlay is more suitable for native internal structure of DataTables. On the other hand, I'm willing to dig into this demand and append more custom code snippets to follow the original intention of design doc.

**Comment by dabeng** [comment]
@mcarrano It seems that maintaining the layout "save&cancel buttons in a panel that extends down from the row " needs more extra js code:

![screenshot from 2018-05-08 23-10-32](https://user-images.githubusercontent.com/5689075/39766357-ac560e64-5316-11e8-8a29-69108dab717d.png)
![screenshot from 2018-05-08 23-10-40](https://user-images.githubusercontent.com/5689075/39766366-b1291d32-5316-11e8-867a-6a653b5a5767.png)

**Comment by jgiardino** [comment]
> can any code from React be reused here or are the implementations just too different?

I was curious to see what we come up with here in core that the react component might be able to reuse.

> In short, keeping save&cancel buttons in the original row rather than in overlay is more suitable for native internal structure of DataTables.

I would also prefer this approach from an html perspective. But as @dabeng mentions above, achieving the design that's documented isn't possible with css alone, and requires additional JS to handle positioning the buttons.

**Comment by jgiardino** [comment]
oops, hit the wrong button to post my comment

**Comment by mcarrano** [comment]
We could rework the design so the buttons fall inline as @dabeng has them. However I think the reason it was designed with the tab hanging below is that we can't necessarily guarantee the width of the last column. I'm sure that's why the table readjusts when a row enters edit.

@matthewcarleton @LHinson interested in your thoughts on this. Is there really such a thing as a pure HTML/CSS example for data tables? How do you think we should handle?

**Comment by dabeng** [comment]
Hi @jgiardino When I created this inline edit for table view demo page, I followed "btn-link" coding style - https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/buttons.html, so I used Glyphicons .

Now, I have replaced Glyphicons with Patternfly icons(fa-check and pficon-close)

@mcarrano I have fixed the issue that column widths change when users switch into edit mode. I also tested this feature on Chrome, Firefox, Safari and Opera.

It's a bit weird that making inline edit action buttons of edited row overlap another row. This is my humble  opinion for reference only.

Please review the updates - https://rawgit.com/dabeng/patternfly/ie-table-view-dist/dist/tests/inline-edit-for-table-view.html

**Comment by jgiardino** [comment]
> Is there really such a thing as a pure HTML/CSS example for data tables?

Part of why this design is impossible without JS is because the buttons that overlay the next row have a border that visually appears to connect with the border of the table row. This requires exact placement to the pixel to pull off. Outside of a table, this isn't impossible with pure CSS, but the css that's required isn't supported very well in the context of a table. It is possible to have buttons overlay the table with some control over the placement, but the visual design would need to be modified to allow for a less precise placement. 

> I have fixed the issue that column widths change when users switch into edit mode.

I'm not sure that setting fixed column widths is a reliable fix for this issue, since I'm not sure that's how consumers will have their data tables set up. I assume that most data table don't have fixed column widths.

**Comment by mcarrano** [comment]
Thanks for your explanation @jgiardino . This leads me to a question of whether there is value in creating a Core example page for this given that we would need to modify the design to make it work without Javascript. @LHinson let's discuss following Summit.

**Comment by dabeng** [comment]
> I'm not sure that setting fixed column widths is a reliable fix for this issue

@jgiardino I have removed the fixed width settings from datatables thead.

https://rawgit.com/dabeng/patternfly/ie-table-view-dist/dist/tests/inline-edit-for-table-view.html

**Comment by jgiardino** [comment]
Hey @mcarrano,
I was playing around with what's possible from a pure css perspective, and thought I would share what I found. In the following example, if I place a `<div>` with buttons in the table cell with the kebab, I can position it so that it's diagonally opposite the bottom left corner of the table cell with the kebab, using the styles shown below. I can also have it perfectly left-aligned with the kebab, but it would be hanging off the right edge of the table.

![image](https://user-images.githubusercontent.com/21063328/39938242-50e68d2c-5520-11e8-8419-8383026998d6.png)

I know this does not look exactly how you would want it to, but thought it would help show what's possible.

**Comment by matthewcarleton** [comment]
Just catching up on this, happy to get involved if I can be of any use. @dabeng I did notice that in safari when in edit mode the rows disappear. http://g.recordit.co/SuiKic4sM9.gif

**Comment by mcarrano** [comment]
@dabeng after discussing with @LHinson , we'd like to put this on hold for now as it appears we don't have a solution that matches the current design without including Javascript. I don't want to revisit the design at this time as we already have a working implementation for pf-react. Thanks for all your efforts on this. I think it will help clarify how we should address this for pf-next.

**Comment by dabeng** [comment]
Hi @matthewcarleton On my safari 10.0.3 (12602.4.8). It works well. 

![9x6mpy9vlw](https://user-images.githubusercontent.com/5689075/40090834-ddb5ef3a-58e6-11e8-9369-0e29eed71f96.gif)

Did you get some errors on console of safari when you loading the demo page ?

**Comment by dabeng** [comment]
@mcarrano Thanks a lot for syncing info. Could you tell me where is the working implementation of "inline edit in table view" for pf-react. I tried out the [Table With Inline Edit Row](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=patternfly-react%2FTable&selectedStory=Table%20With%20Inline%20Edit%20Row&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs). It seems that this example doesn't match the  [current design](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#inline-edit-in-a-table-view).

![uu5zqslcpi](https://user-images.githubusercontent.com/5689075/40091444-565fb314-58ea-11e8-8b4a-ffe97fd9d8d3.gif)

**Comment by mcarrano** [comment]
@dabeng There seems to be some issue with the correct version no longer displaying in the React showcase. @jgiardino did you ever figure out what's happening here?

**Comment by jgiardino** [comment]
Yep, I created an issue and it's now fixed. If you still see issues, you might want to try clearing your cache to reset the css.

**Comment by LHinson** [comment]
Closing this one as we will not address at this time. See Matt's comment above from May 14
