### ISSUE TITLE
CSS on pficon-user is inconsistent with other icons

### ISSUE THREAD

**Issue by mechevarria** [patternfly/patternfly-3#1090]
I noticed that the pficon-user element does not line up like other icons.  I included some screenshots to show the issue.  The fix is to remove the `float: left` from the element.
![problem2](https://user-images.githubusercontent.com/2657771/42397195-eea247a2-8132-11e8-8bf9-69bf4f6933d1.png)
![problem1](https://user-images.githubusercontent.com/2657771/42397196-eeb234fa-8132-11e8-9e24-1c55f8650b9f.png)
![fix](https://user-images.githubusercontent.com/2657771/42397197-eebed390-8132-11e8-933e-c77d63b2af6d.png)

**Comment by dgutride** [comment]
This appears to be a bug on patternfly-ng and not on core css.

**Comment by LHinson** [comment]
@mechevarria I'm having a hard time pinpointing where the bug is here. 

If I look at patternfly-core, I don't see this dropdown with the caret. See: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-primary-only.html

If I look at patternfly-ng, I see issues with icon alignment but not the issue with the alignent/caret. See: http://www.patternfly.org/patternfly-ng/#/verticalnavigation

Will you clarify which implementation of PF is used (e.g. PF-core or PF-ng) as well as exactly which component contains this bug?

**Comment by mechevarria** [comment]
This issue can be closed.  I used the example html from the first link you sent to create the user dropdown menu and there were no css issues.  The fixed code is used is here (lines 35-45)

[https://github.com/mechevarria/patternfly-ng-seed/blob/master/src/app/nav/nav.component.html](https://github.com/mechevarria/patternfly-ng-seed/blob/master/src/app/nav/nav.component.html)

I am using the vertical-navigation component from patternfly-ng.  Its example code does have this problem though.  If you look at the user menu there is extra space under the icon when you hover and the dropdown menu goes into the nav bar.  The fix is to have the example code for the vertical nav component be updated to reflect the html in patternfly core
