### ISSUE TITLE
Textbox Filter Bug

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-3#1116]
Related to: https://github.com/patternfly/patternfly-design/issues/695

- The text box filter should work as a Select list (either single or multiple) with placeholder text. You can see that behavior if you go to this page and scroll down to [Placeholder](http://silviomoreto.github.io/bootstrap-select/examples/ ). The placeholder text should not appear in the menu. 
- When you clear the filters, the placeholder text should be restored.

**Comment by dabeng** [comment]
Hi @LHinson @mcarrano . After looked into the issue( patternfly/patternfly-design#695), I found that [current filters](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/filter.html) of patternflly-core repo are built up based on [bootstrap button dropdowns](https://getbootstrap.com/docs/3.3/components/#btn-dropdowns). Are you sure you want to replace all of them with [bootstrap select](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/bootstrap-select.html).

**Comment by mcarrano** [comment]
Good question @dabeng .  I didn't realize this. Given that these are already implemented as dropdowns, is there any reason that the placeholder text must also live in the menu? Seems like that should just be the label of the button and the menu includes things you can select. Does that make sense? What would your recommendation be on how best to address this?

**Comment by dabeng** [comment]
@LHinson @mcarrano Perhaps we need to achieve unity in understanding.

1. @akaRem put forward two issues. One is about textbox filter(input filter). Feel free to play around with the associated [demo page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view.html#). You will find that with the help of textbox filter of patternfly-core repo, users could create active filter labels by inputting key words and then pressing "enter" key. If users just click textbox, nothing happens.

2. The second issue is about select filter. We just need to replace the first item of dropdown menu with "no filter". If users select the option "no filter", the placeholder text will reappear. Am I making myself clear 😊

**Comment by mcarrano** [comment]
@dabeng for (1) not sure I see what the issue is. Seems to work as expected.

For (2), we could add "no filter" to the menu. However this would mean that selecting that option should clear any existing filters which is not currently the case. I looked at how this is working today in both Angular and React PatternFly and they are not consistent. Please hold on this for now until I can get more input about how we want/expect this to work.

**Comment by akaRem** [comment]
@dabeng The playground you provided is ok in general. But how can I reproduce original issue with placeholders and no-filter stuff?

I mean this playground does not include UI case like this
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1472728/42732260-c23e4a30-8826-11e8-8d44-b3e543b86ed3.png">
(Drop-down with pre-populated items)

BTW, should this input have autocompletion or not?
<img width="384" alt="image" src="https://user-images.githubusercontent.com/1472728/44006923-04d7e674-9e95-11e8-9ff7-b79adcc644dc.png">

**Comment by mcarrano** [comment]
@dabeng After more discussions with the PatternFly design leads, we'd like to see if we can make this work without needing to have either placeholder text or a 'null' item in the list. Can we create another demo that replaces the dropdown with a select list that uses placeholder text? I'd like to see what this looks like and then investigation the implications of making that change. Let me know what you think.

**Comment by mcarrano** [comment]
@dtaylor113 Thanks for taking this on. Just to summarize out meeting today, Dave will explore ways to implement this without requiring the placeholder text to exist in the menu and create a prototype. Expected interaction is that...

- User selects an option from the list and it replaces the placeholder text with the selection as that filter is applied.
- A filter chip with the new filter is added to the filter bar.
- To remove the filter, the user clears the filter chip. Upon removing the filter the placeholder text will be restored.

@dtaylor113 is this consistent with your understanding?

**Comment by dtaylor113** [comment]
@mcarrano, yes, however wondering about another usecase:
1. User selects an option from the [ex 'Month'] list and it replaces the placeholder text with the selection [ex: 'July'] as that filter is applied.
2. A ['Month: July'] filter chip is added to the filter bar.
3. User selects another filter type, ex: Name
4. User switches back to Month filter.  Should the placeholder be shown or the previously applied 'Month' value (ex 'July')?

It will be difficult to have the filter remember it's previous value.  I would advocate the placeholder be shown in this case, and if another 'Month' filter is applied, and it's single select, the month filter chip is replaced/updated with the new month that has been selected.

I think this is correct as _Placeholder..._ in this case is giving instructions on applying a filter, not what filters have been applied.

**Comment by mcarrano** [comment]
Hmmm...  Interesting question @dtaylor113 . I would prefer that the filter control be aware of what filters are currently applied and reflect that. But if that's too hard to do, then I guess your proposal is the next best alternative.

Just added above:
> I think this is correct as Placeholder... in this case is giving instructions on applying a filter, not what filters have been applied.

**Comment by johnnyNcsu** [comment]
Apologies for interjecting, and not to muddy the waters here, however, I have looked at pfFilter extensively. @dtaylor113 , if I'm not mistaken, you are proposing to (in effect) prevent the user from choosing (in your example), the month 'July' and then later choosing another month (ex: 'June'). The implication being that this would result in two filters for the month column which, depending on the kind of data, might be mutually exclusive (single select?) One problem I see with this proposal is that there may be data where a determination of mutual exclusivity is not clear. For instance, I am using this module to render a wide range of csv files that often contain data that do not fit neatly into well defined categories.

The way pfFilter works currently, the user is permitted to apply as many filters to a single column as she would like - even if the result is zero rows being returned, which is a valid outcome if the filters are chosen narrowly. When this occurs, it is hopefully clear from the filter chips in the menu bar why the outcome returned no result and the user can remove/redefine filters as needed.

For my own use, I have modified pfFIlter to include additional capability to support custom filtering and for the option to apply a custom filter immediately upon selection from the drop down menu (rather than waiting for a search string to be entered into the input field). In addition, I also addressed the original bug in this thread of restoring the placeholder text when all filters are cleared. While not completely consistent with the proposals you are considering, the changes are backwards compatible with the current pfFilter behavior and may be useful to a wider audience. I am planning to offer them back to PF, pending approval from my employer (this can take a while - lawyers). Sadly I have no way to know how much longer this will take so I understand if you move forward before I have the opportunity to contribute these changes for your consideration. Thanks.

**Comment by dtaylor113** [comment]
Hi @johnnyNcsu, thank you for your comment.  Yes, for my example I am illustrating single-select and mutal exclusivity, however, where possible we are striving to provide the app dev the ability to specify whether single or multiple filters can be applied to a single column.

**Comment by mcarrano** [comment]
@johnnyNcsu Yes, the current approach assumes that the control applies a single mutually exclusive filter. It seems like that's what pfFilter is doing now so I'd be interested to know how you were able to get this to work for applying multiple filters. Are we talking about the same Angular implementation here? https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter

We did talk about the idea of extending this to allow multi-selection of values, so you could filter for events in January OR February, for example. Would that address your use case? If and when you are able to share your implementation, we'd definitely be interested in this. We have talked a lot about the need to extend our filtering approach to address the use cases you describe.

**Comment by dtaylor113** [comment]
Related PR: https://github.com/patternfly/patternfly-ng/pull/449

**Comment by johnnyNcsu** [comment]
@mcarrano @dtaylor113 , here is a [rawgit demo](https://rawgit.com/johnnyNcsu/patternfly/master/index.html#) of the changes I made to pfFilter for my use (as described above). The last two items in the filter pull-down ('CSS Grade C or Better' & 'Apple Platforms') are custom filters that act immediately upon select. This is an extension to the existing filter behavior with (hopefully) no change to the original behavior (except for restoring the placeholder when all filters are cleared). Note that the filter input box remains active even for the custom filters - this may or may not be a desired behavior (from a given UXD perspective) but it seemed fine to me to allow this; I can see situations where this may be undesirable however.

The intent of these changes is to cover situations where you may want to encode complex logic into a filter. For example, suppose company A has a personnel data base that they render in a table. They may want to filter on employees eligible for retirement. Suppose retirement eligibility depends not only on employee age but also years of service with the company and perhaps the requirements for age and/or service years have changed over time resulting in a complicated set of conditions to fulfill. You could encode this logic into a custom filter function that operates across any number of table fields to return the correct results in a single filter operation.

Since I am not fully aware of the UXD objectives for the project, I understand completely if this implementation is not consistent with your objectives and therefore not suitable for consideration (i.e. don't worry about hurting my feelings if these changes are not appropriate). Thanks.

**Comment by dtaylor113** [comment]
> Note that the filter input box remains active even for the custom filters - this may or may not be a desired behavior (from a given UXD perspective) but it seemed fine to me to allow this; I can see situations where this may be undesirable however.

HI @johnnyNcsu, I understand your usecase, however I'm not sure the use of the Placeholder text is quite correct for your custom filters.   Placeholder text is supposed to be instructions on what I user can enter or select.  IMO it is not supposed to be used to reflect what has been selected; like it does for your custom filters.   
Other than that, I like what you have done! :-)

**Comment by johnnyNcsu** [comment]
@dtaylor113 , Thanks.

> Placeholder text is supposed to be instructions on what I user can enter or select. IMO it is not supposed to be used to reflect what has been selected; like it does for your custom filters.

Well - it kinda does both. For instance, if you select 'Apple Platforms', you will get all the Apple related platforms and if you then enter 'Mac' in the input field, you refine the results for 'Filter by Apple Platforms ...' by showing only those Apple platforms that are identified as Mac. I agree that the implementation could be cleaner however. I'm definitely interested to see how the design is resolved. Let me know if you want me to issue a PR for what I have done and I'll do that when I get the ok (unless OBE).

**Comment by mcarrano** [comment]
@johnnyNcsu Thanks for sharing this. I definitely think it offers some good ideas for future considerations. We have talked a lot about how the user can save and recall custom filter queries for reuse, so I think this shows one viable way to extend our current filter pattern for this.

Doing this is definitely beyond the scope of what this issue is intended to address, but it is definitely something we will keep in mind.

**Comment by dtaylor113** [comment]
Hi @mcarrano & @amarie401,  I'm working on implementing these changes in PF Core.  
As discussed [here](https://github.com/patternfly/patternfly-react/pull/558#discussion_r213324535) I need to add `.filter-pf-select-dropdown.filter-selected` css so that selected values in the dropdowns are not italicized.  Also, I need to remove placeholder values from the example filter dropdowns.

I see two places where I need to make these changes:
1. In the [filter test page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/filter.html#) the Car filter which has default selected `Subaru` & `Crosstrek` dropdown values which should not be italicized. Also placeholders need to be removed from dropdowns. 
2. In [pf.org -> Textbox Filter -> Code](https://www.patternfly.org/pattern-library/forms-and-controls/textbox-filter/#code).  -same changes

I believe I need to add the new css to patternfly/patternfly repo. and update filter test page.  Once this PR is merged, I'd need to update patternfly/patternfly-org to latest patternfly version, and adjust the Textbox Filter -> Code example.  

Is this the correct approach, and have I missed any other 'core' areas?  -thanks
CC @jeff-phillips-18

**Comment by mcarrano** [comment]
That ll sounds correct to me @dtaylor113 .  Also looping in @matthewcarleton in case he has any input.

**Comment by amarie401** [comment]
@dtaylor113 pf-org is including the html that lives in `widgets/forms/filter.html` in pf3. No changes should need to be made in the `code.md` file in pf-org unless the directory for this example in pf3 changes. If it is only CSS updates being made then it should just require a rebuild of travis for pf-org to pick up the changes and update the version. You could also update to the latest version manually but I don't think you'll need to do that if you re-run the pf-org travis build.
