### ISSUE TITLE
Create a test page that includes sidebar working w/ the vertical nav

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-3#1118]
Create a test page that includes sidebar working w/ the vertical nav. Related to #512. 

Side bar can be seen in this test page here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/form.html

Create a new test page using the above from page with vertical nav vs horizonal nav.

**Comment by dabeng** [comment]
@LHinson @andresgalante @dgutride I created a [test page](https://rawgit.com/dabeng/patternfly/vnav-sidebar-dist/dist/tests/vertical-navigation-with-sidebar.html) that includes sidebar working w/ the vertical nav. Could you review it whenever you have the chance ?

**Comment by dabeng** [comment]
FYI, due to its own bug , [fixed-height accordion](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/accordions.html) can not be used in the above layout to implement the following feature:
https://github.com/patternfly/patternfly/issues/512#issuecomment-327736464

> would be even better if the accordions below the expanded one would be snapped to the bottom of the page.

**Comment by LHinson** [comment]
I see the bug now @dabeng. What options do we have to fix?

**Comment by jeff-phillips-18** [comment]
What bug in fixed-height-accordion?

**Comment by dabeng** [comment]
@jeff-phillips-18 @dgutride @LHinson @mcarrano  IMO, there are some bugs inside fixed-height accordion.
1. When you expand one panel, the below panels will slide down firstly and then slide up.
![peek 2018-08-08 06-56](https://user-images.githubusercontent.com/5689075/43808731-f14fd114-9ae0-11e8-9f53-b25e8dd55d75.gif)

2. current [fixed-height accordion](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/accordions.html) doesn't work if you change the "height setting" in the following code snippets:
```html
    <h2>Fixed Height</h2>
    <div class="panel-group" id="fixed-accordion" style="height: 350px;">
```

3. Fixed-height accordion doesn't work if users set relative height(e.g `height: 100%;`) for it

4. If scrollbar is not at the top of panel-body, the bottom-border will disappear as shown below:

![screenshot from 2018-08-08 08-48-19](https://user-images.githubusercontent.com/5689075/43810370-de1ae288-9ae9-11e8-9e84-4b14bcba0b7f.png)

![screenshot from 2018-08-08 08-51-24](https://user-images.githubusercontent.com/5689075/43810377-e3ae7e80-9ae9-11e8-93ad-450a9608834b.png)
 5. If panel-heading includes a long text, current indentation setting is not good enough.
![screenshot from 2018-08-08 09-22-28](https://user-images.githubusercontent.com/5689075/43811023-2c8b4bbc-9aed-11e8-9435-03f12a544091.png)

6. When users use tab key to move keyboard focus between different panel-headings, they don't know which is the focused panel-heading since there is no highlight or focused effect. In comparison, bootstrap accordion adopts underline:
![screenshot from 2018-08-08 09-40-54](https://user-images.githubusercontent.com/5689075/43811518-6d292174-9aef-11e8-8e37-45babfd26be3.png)

7. Keyboard navigation of fixed-height accordion with "tab key" doesn't work well on Firefox 57.0b12 (64-bit)
![peek 2018-08-08 11-22](https://user-images.githubusercontent.com/5689075/43814778-dae6e214-9afe-11e8-9f72-ab0fa59256c6.gif)

In comparison, [bootstrap accordion](https://getbootstrap.com/docs/3.3/javascript/#collapse-example-accordion) works well with tab key navigation.
![peek 2018-08-08 11-24](https://user-images.githubusercontent.com/5689075/43814789-e04e7028-9afe-11e8-8747-08c325123805.gif)

**Comment by jeff-phillips-18** [comment]
Most of what you indicate above is basic accordion behaviors/issues. The `Fixed` height accordion is meant to be `Fixed` height, meaning it has a fixed height not relative height. Changing the height attribute in the style setting using dev tools will not update obviously, but if you were to then resize the window it would.

None of this causes the sidebar issue or prevents it from being in the sidebar. However, I have put up PR #1123 for a flexbox version of the fixed height accordion that might be more suited based on some of the other asks.

**Comment by dabeng** [comment]
Sorry, I should give more details : )
1. from my point of view, fixed-height accordion is meant to full-height accordion like http://jqueryui.com/accordion/#fillspace

2. If `The Fixed height accordion is meant to be Fixed height, meaning it has a fixed height not relative height.` Such accordion is less useful than full-height accordion.

3. I changed height attribute within source code rather than dev tools.

**Comment by jeff-phillips-18** [comment]
Here's a crack at the sidebar in vertical nav with the new fixed height accordion:

[Test Page](https://rawgit.com/jeff-phillips-18/patternfly/vert-nav-sidebar/dist/tests/vertical-navigation-with-sidebar.html)

(needs some work for mobile resolutions)

**Comment by LHinson** [comment]
@skateman revisiting some older issues.... did this test page help? we're sweeping old issues so I'm going to close this unless I hear otherwise.
