### ISSUE TITLE
Add new drag handle icon to PatternFly icon set

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-3#1131]
There is a request to add a new icon to indicate dragable rows in a list or card view. The icon has been designed. This was initially files in the design repo as https://github.com/patternfly/patternfly-design/issues/691

**Comment by serenamarie125** [comment]
@LHinson it looks like we need a core developer to be assigned to add this.  Is this something can be addressed asap?  I think at one of our August meetings, we thought that putting the icon into PF would be quick & easy, and that updating the patterns would be a follow on since there were some other design items that had to be addressed first.  Let me know your thoughts!

**Comment by LHinson** [comment]
@serenamarie125 can you or someone else attach the appropriate assets required to add this icon?

**Comment by serenamarie125** [comment]
@LHinson sure, this is associated with https://github.com/patternfly/patternfly-design/issues/691, and @maryshak1996 should be able to help with visual assets if they aren't included there.

**Comment by maryshak1996** [comment]
@LHinson here is the SVG for the drag-drop icon. let me know if there are any other assets that you guys need! 
[pficon-dragdrop.svg.zip](https://github.com/patternfly/patternfly/files/2388836/pficon-dragdrop.svg.zip)

**Comment by serenamarie125** [comment]
thanks @maryshak1996 !

**Comment by LHinson** [comment]
@matthewcarleton will handle this one.
