### ISSUE TITLE
BarChart overlapping Bootstrap column in Listview

### ISSUE THREAD

**Issue by jamesdecourcy** [patternfly/patternfly-3#1161]
I'm trying to put a bar chart in a PatternFly ListView using Bootstrap columns. The problem I'm having is that the Bar chart does not seem to respect the containing column (col-md-3) and overlaps its neighbouring column (col-md-9).

![capture1](https://user-images.githubusercontent.com/2912085/50398163-604d0200-076d-11e9-973e-1e96c10a4418.JPG)

However, as soon as you resize the browser the bar chart resizes itself correctly.

![capture2](https://user-images.githubusercontent.com/2912085/50398179-75299580-076d-11e9-8b28-fb874c702e5f.JPG)

Here is a Codepen which shows the issue. https://codepen.io/james-de-courcy/pen/ZVKLLq (Click "Event One")

**Comment by jeff-phillips-18** [comment]
C3 sets the width/height of the chart based on its parent's size unless you specify the size in the chart config settings. Since the expansion area is hidden, it must be looking upwards until it finds a shown component. If you can set a size.width value on the config rather than using row/column it would resolve the issue. If you are set on using bootstrap row/col, then you may need to trigger a resize event when the item is expanded.

**Comment by LHinson** [comment]
@jamesdecourcy hopefully Jeff's explanation helped. I'm going to close this issue, reach out with any other issues.
