### ISSUE TITLE
Sidebar + Datatable = broken sidebar

### ISSUE THREAD

**Issue by lukebrooker** [patternfly/patternfly-3#121]
Any reason for this code?

``` javascript
$(document).ready(function () {
  // Call sidebar() on ready if .sidebar-pf exists and .datatable does not exist
  if ($('.sidebar-pf').length > 0 && $('.datatable').length === 0) {
    $.fn.sidebar();
  }
});
```

We have pages that have a sidebar and datatables and this seems to be stopping the sidebar calculate its height on those pages.

Sidenote: flexbox can be used to get this functionality just in CSS.

**Comment by lukebrooker** [comment]
As soon as you resize the window, it fixes it because of this:

``` javascript
$(window).resize(function () {
  // Call sidebar() on resize if .sidebar-pf exists
  if ($('.sidebar-pf').length > 0) {
    $.fn.sidebar();
  }
});
```

So not sure why it ignores datatable pages on init.

**Comment by rhamilto** [comment]
Hi, @lukebrooker.

Sorry for the lack of documentation on this.  We'll address the issue in a forthcoming reboot of the PatternFly site.

That said, the fix is to call sidebar() on callback of the data table initializer.  See lines 589-598 of https://github.com/patternfly/patternfly/blob/master/tests/tab.html#L589.  If this is not done, the sidebar height will be incorrectly calculated as the data table transform won't have finished executing before sidebar does.

Given that PatternFly 1.x was supporting IE8 and the current version, 2.x, supports IE9, we can't make the jump to flexbox just yet.  :(

I hope that helps.
Robb.

**Comment by lukebrooker** [comment]
I thought it may be something like that.

Thanks.
