### ISSUE TITLE
Another option for login

### ISSUE THREAD

**Issue by thescouser89** [patternfly/patternfly-3#15]
From https://www.patternfly.org/wikis/patterns/user-authentication/loginlogout/ , the login page is really stunning!

However, I'd like to have another supported option for login. Clicking on the 'Login' button will provide a pop-up that will ask for Login credentials. That will, IMO, probably make the Login process more seamless and fluid. If the user decides he doesn't want to login after all, he/she can just click on [x] or any other part of the screen to get out of the Login pop-up.

**Comment by mcarrano** [comment]
Hi Dustin,

I think that you raise a really good question and I wanted to expose this to the PatternFly mail list for further comment.  See my thoughts below.  We are continually growing and revising the library so we can consider this for a future iteration.

Matt

----- Original Message -----

**Comment by thescouser89** [comment]
https://trello.com/b/4u4TcAVi/wildbee

I think Trello shows very well what I'd qualify as 'seamless' login. Users can view the information, and if they want to edit something, they can sign-in if they are not already. I'd think this is very useful in the case of a dashboard scenario (Jenkins, some monitoring tools).

I'm not sure if that answers your question or not :)

**Comment by mcarrano** [comment]
Yes, I do think this is a valid scenario to consider for a future iteration of the library.  Thanks for you input about this.

-Matt

----- Original Message -----

**Comment by xtrasmal** [comment]
@thescouser89, @mcarrano  
Popups/Modals are already available. So add a button in the navbar which opens one called login. 

Why no other login scenario? Well because a loginform popup is nothing less than a form in a modal.
Patterfly already has scenario's for a login form. Patternfly also has scenario's for modals.

Consider this: 
Logged in:
![image](http://sc-cdn.scaleengine.net/i/c320aaab4136b1d39cb639346374acb1.png)
Logged out:
![image](http://sc-cdn.scaleengine.net/i/09f447beb62bd5add324b813fd117eb1.png)

The current dashboard shows a dedicated place where the username is shown. So in other words: It shows the current logged in user. So it is a dedicated place for an auth indicator. This can be used to display the word LOGIN, when nobody is logged in. This is perfectly fine, because it is a dedicated place for an auth indicator. 
Every Patternfly based app user will always understand to look to the top right of the screen to find the LOGIN, LOGOUT, USERNAME + Dropdown. 

## 

We need to remember that not all applications build on Patternfly will have the same user interface. Most applications will have the same buttons on the same place, but considering that most applications will have loads of buttons to increase usability in unusual places.

In one of my apps build on bootstrap I have a table which shows all users. AngularJS handles sorting. I do not want the user to leave the screen when ACTIVATING, BANNING, DELETING an user. 
![image](http://sc-cdn.scaleengine.net/i/e9b0ebc2652c1271f57b72e7562fea74.png)

In the example above I have 4 buttons. The first 3 trigger a modal with a confirmation button. The last one take you to the profile screen. 

I do not expect Patterfly to create use-cases for every single scenario.

## 

Remember that you are handed guidlines for design. But functionality will be so diverse that requests like @thescouser89 made will be one of many that will lead to extremism.

**Comment by xtrasmal** [comment]
Is this repo still managed or what is going on? - ticket can be closed

**Comment by rhamilto** [comment]
Hi, Xander.

Yes, this repo is actively being managed.  This issue remains open because we've not decided if and what PatternFly will offer concerning additional login options.  And I'm not saying PatternFly _will_ offer additional login options.  It simply has not been decided yet, which is why the issue remains open.

Thanks!
Robb.

**Comment by rhamilto** [comment]
There are no plans to extend or modify the login page at this time.
