### ISSUE TITLE
Wrong path for bootstrap in examples

### ISSUE THREAD

**Issue by thescouser89** [patternfly/patternfly-3#16]
Hi,
- I've noticed that most (or all?) of the examples in the project (inside the test folder) defines the wrong path for `bootstrap.min.js`. In this case, the folder does not exist.
  e.g https://github.com/patternfly/patternfly/blob/master/tests/accordions.html#L19
- I've also noticed that my browser could not display some icons.
  OS: Fedora 20
  Browser: Firefox 29
  ![screenshot from 2014-05-01 13 55 37](https://cloud.githubusercontent.com/assets/630746/2855235/5f75c270-d15a-11e3-82c1-0832bf9819ed.png)
- Last thing I wanted to mention was that the example uses 
  `<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>` [1]
  This would work fine if the examples were put in an HTTP server and we would launch it with `http://<example>/dashboard.html`  . However, I would think that users will usually launch it from the file itself with `file:///home/dcheung/<extra_paths>/dashboard.html`, and in that case, the JQuery code won't be downloaded.
  So I'd suggest we switch to `http://code.jquery.com/jquery-1.10.2.min.js`

[1]: e.g https://github.com/patternfly/patternfly/blob/master/tests/dashboard.html#L15

**Comment by thescouser89** [comment]
I'd be willing to provide a PR if someone would tell me what I should proceed to fix these issues :)

**Comment by rhamilto** [comment]
hi dustin,

have you installed the dependencies?  the pathing is correct if the dependencies have been installed.

this is an issue with firefox; it will not serve web fonts without a web server (over http or https).  if you utilize the integrated grunt server you should not have an issue.

the jquery call is intentionally protocol agnostic so that it works under both http and https.  it's really best to run patternfly against a web server.

hope that helps,
robb.
