### ISSUE TITLE
big gap between modal dialog content and buttons

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-3#181]
There is a big gap there is between the dialog content and the action buttons of the dialog.
modal-body adds 15px of padding, modal-footer adds 14px of padding+15px of margin-top.
Elements inside the dialogs, such as form-group also tends to add 15px more.
If I'm doing the math right, that's 59px total between a text entry box and the action buttons.
This makes dialogs quite tall.

**Comment by rhamilto** [comment]
@andreasn, are you referring to the example at http://rawgit.com/patternfly/patternfly/master/tests/modals.html?

**Comment by andreasn** [comment]
Yes, that's the one!

**Comment by rhamilto** [comment]
Thanks, @andreasn.  Let me defer to our visual design lead, @kybaker.  What do you think, @kybaker?

**Comment by LHinson** [comment]
I know @kybaker is swamped this sprint so I went ahead and filed a bug in Jira (https://patternfly.atlassian.net/browse/PTNFLY-1124) We will make sure to get it taken care of.

**Comment by andreasn** [comment]
Thanks!

**Comment by kybaker** [comment]
@andreasn @rhamilto:
I understand the concerns about the height. When we designed PatternFly one of the goals was to present dense IT data in a lighter more consumable way. The primary way we do this is with whitespace. We also use the whitespace to create a visual hierarchy instead of using boxes or other ornamentation which creates visual noise. 

I understand there are specific situations where the spacing will need to be reduced. In general we should maintain the spacing for the PatternFly base example and allow users to customize the pattern for their needs.

**Comment by LHinson** [comment]
@andreasn given @kybaker recommendation re: spacing, I'm going to close this issue.
