### ISSUE TITLE
Font awesome only

### ISSUE THREAD

**Issue by xtrasmal** [patternfly/patternfly-3#19]
Bootstrap uses this: http://fontawesome.io/icons/

I add the icons by doing this:  

``` html
<span class="fa fa-user"></span> 
```

Why is patternfly using Icomoon? 
It causes freak implementations:

``` html
<span class="pficon pficon-user"></span>
```

**Comment by rhamilto** [comment]
Hi, Xander.

I'm not sure I entirely understand your question.  Bootstrap includes Glyphicons (http://getbootstrap.com/components/#glyphicons).  The markup pattern for Glyphicons is `<span class="glyphicon glyphicon-search"></span>`.  Since PatternFly is based on Bootstrap, it also includes Glyphicons, and the markup pattern is the same.  PatternFly _adds_ Font Awesome (e.g., `<i class="fa fa-car"></i>`) and some custom icons generated using http://icomoon.io/ (e.g., `<span class="pficon pficon-add"></span>`) since neither Glyphicons or Font Awesome met specific visual needs for the icons we added.  As for markup, the html element used is irrelevant since both `<i>` and `<span>` are semantically neutral.

Can you clarify the issue you're having?

Thanks,
Robb.

**Comment by xtrasmal** [comment]
@rhamilto You are right.  It seems like patternfly.css expects the folder structure to contain a components folder. Instead I have a assets/bower_components/  folder structure. 
Problem solved thanks.
