### ISSUE TITLE
Legend with many items makes donut chart too small

### ISSUE THREAD

**Issue by skateman** [patternfly/patternfly-3#266]
![screenshot from 2016-04-27 13-44-19](https://cloud.githubusercontent.com/assets/649130/14851310/506794ae-0c7f-11e6-876c-1751a1d650d7.png)

**Comment by LHinson** [comment]
@skateman Even if that donut chart was larger, it would be very hard to read since there is so many categories. Our documentation [1] suggests that you "use no more than six categories" for the donut chart. Consider reducing the number of categories or using a bar chart [2] instead.

[1] https://www.patternfly.org/patterns/donut-chart/
[2] https://www.patternfly.org/patterns/bar-chart/

**Comment by skateman** [comment]
cc @panspagetka @martinpovolny

**Comment by martinpovolny** [comment]
We currently cannot change the chart type based on data. And there's no plan to do that.

What can we do?
- we leave it like this
- patternfly does something about it
- we do some changes to the patternfly styling to do something about it
- we can limit the length of the labels in the legend to make it smaller (such as 20 letters)

Unfortunately the recommendation by patternfly does not match the usecases we have in the product. 

Can we do something to better inform patternfly about the usecases and needs of ManageIQ?

**Comment by martinpovolny** [comment]
@dclarizio: is it ok for us to change the number of items in the build-in reports?

So that only top 5 + "other" are displayed for pie charts and do similar limitation for other chart types based on patternfly recommendation?

Or can we switch the chart types e.g from pie to bar and similar as needed for the build-in charts?

**Comment by dclarizio** [comment]
@martinpovolny @LHinson For the sample charts, we can reduce the number of elements and/or change the chart type, but the reporting system does allow the user to choose up to 10 plus an "other", so that doesn't really solve the problem for the product as customers may already have charts with this many items that they need to show.  I would rather limit the text length (chop it with "..." at the end and have hover text as backup) as well as a smaller font to try to fit the legend in a single column.

If we decide certain types (like pies and donuts) can only handle a lower max number of entries, then we will have to add code to limit that and probably not show some entries for existing charts that have too many.  In this case, we may need to validate with product management as to what limits we can set.

**Comment by martinpovolny** [comment]
@dclarizio : I am not sure if patternfly is able to deliver that unless they actually try to play with charts in ManageIQ. 

We do not need cool charts. We need cool charts that show the data that we have in the product.

**Comment by dclarizio** [comment]
@LHinson This is typical to what we see on most charting sample pages, the samples have a low number of legend values that are all short text, so the charts are easy to layout.  In reality, we often need to place things like VM names and such that can have quite lengthy text.

With our current flash pie charts, we are able to handle I think 12 to 15 character long names and up to 11 of them stacked vertically next to the chart.  For this reason, we allowed that many to be defined when creating the charts and users can swap between the different types at will as they design their reports/charts.

If we have to limit donuts and/or pies to less legend items, we will have to either change the editor to limit the number for these types of charts or just not show past 6 when the chart is rendered.  We can do that, but users with already defined charts will lose data visibility.

We should probably take this offline with samples of existing vs new charts so we can look at various solutions.

**Comment by LHinson** [comment]
@dclarizio @martinpovolny looping in @serenamarie125 to help assist on a recommendation specific to your product needs that can be addressed in the short term. For the long term, samples and use cases to help inform PatternFly design is great! I love this suggestion. @serenamarie125 should be able to help out in this area as well.  Once we have that information, we will need to look at it and evaluate if this is a common problem that PatternFly can address.

**Comment by LHinson** [comment]
Looping back around on this one. Were you able to resolve the problem in your product @serenamarie125 @dclarizio @martinpovolny? If so, I'm going to close this issue out.

**Comment by martinpovolny** [comment]
As far as I know we have not. Ping @PanSpagetka.

**Comment by PanSpagetka** [comment]
Yep this is resolved. We have shortened legend and full description in tooltip. For dashboard charts we have zoom option. It could be problem for some extreme cases, but I guess you can close it.

**Comment by LHinson** [comment]
OK, thanks for the update @PanSpagetka. I'm going to close this one.
