### ISSUE TITLE
typeahead or autocomplete is very popular plugin which should be introduced into patternfly

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#332]
Maybe [Bootstrap-3-Typeahead](https://github.com/bassjobsen/Bootstrap-3-Typeahead) is a good choice.

**Comment by LHinson** [comment]
Yes, I think this would be helpful from a design perspective. We would need to post some docs to the site to ensure that people know that we have this.... that can come after though. 

@andresgalante has suggested sending a e-mail to the mailing list to see what people are using since there are many autocomplete plugins. Do you want to initiate that conversation?

**Comment by andresgalante** [comment]
I don't think we should add it to patternfly at the moment but we can revisit the idea if we have products needs for it.
