### ISSUE TITLE
The global scrollbar is unnecessary on vertical navigation demo page

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#338]
![screenshot from 2016-07-07 10-42-52](https://cloud.githubusercontent.com/assets/5689075/16641263/71599730-43c4-11e6-9ea7-658102d1c775.png)

With all due respect, it would make more sense to create a scrollbar with the staring point at position(2).

**Comment by andresgalante** [comment]
@dabeng This was a discussion we had and thats why we've ended up with so many alternative layouts:
https://rawgit.com/patternfly/patternfly/master/tests/

In order to have an inner scroll we would need to measure too many stuff and add more CSS and JS than we wanted. It's not a price I am willing to pay. But I will leave this issue open in case others feels otherwise and we can restart the discussion.

Thanks again @dabeng

**Comment by dabeng** [comment]
@andresgalante  The global scrollbar is the root cause of this [issue](https://github.com/patternfly/patternfly/issues/352).

**Comment by michpetrov** [comment]
Hi @andresgalante, is there an issue with using [viewport units](https://developer.mozilla.org/en-US/docs/Web/CSS/length#Viewport-percentage_lengths)?

At first glance it looks like all that is necessary is to set the content height as something like

    height: calc(100vh - <navbar-height> - <margin-top>);

The result looks like [this](https://rawgit.com/michpetrov/patternfly/content-height-dist/dist/tests/vertical-navigation-primary-only.html).

**Comment by andresgalante** [comment]
@michpetrov you are right, we can do it with `vh` since we don't have the options with footer and alt layouts anymore.

**Comment by LHinson** [comment]
For PatternFly, we would like to proceed with the current solution for the sake of simplicity so I'm going to close this issue. Thanks for the suggestions.
