### ISSUE TITLE
Panel body section of accordion should be displayed with scrollbar

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#339]
![screenshot from 2016-07-07 12-00-56](https://cloud.githubusercontent.com/assets/5689075/16642164/b0087128-43cd-11e6-8ca3-4413f79e72f7.png)

I guess I got the point of the accordion creator that the whole accordion has a fixed height limitation and the panel body section will use scrollbar to show the entire content.

**Comment by andresgalante** [comment]
I agree, lets improve that by adding more text on the widget, we should also move the fixed height accordion after the regular accordion instead of at the end of the list.

Adding more text is part of this repo, moving the widget up is an issue for the website repo, I'll open it there reference this one.

Do you want to send a PR adding more text to the widget?

Thanks a lot!

**Comment by dabeng** [comment]
Of course, it's my pleasure. Maybe there will be some code snippets modification except for supplementary description :blush:

**Comment by andresgalante** [comment]
@dabeng is this one fixed? can we close it?
