### ISSUE TITLE
No dist directory created when installing with npm

### ISSUE THREAD

**Issue by lroitman** [patternfly/patternfly-3#391]
Hi
I am trying to install the latest patternfly version with npm install. After doing so no dist directory is being created under node_modules/patternfly

There was no such problem before version was bumped to 3.8

All the documentation still refers to scripts located under patternfly/dist.

My node version is v6.2.2, npm version 3.10.2, I am running Windows 8

**Comment by priley86** [comment]
Hi @lroitman - thanks for mentioning this to us! We recently added the `dist` folder to our `.gitignore`, but forgot to add a `.npmignore` so that it could be included in our NPM distribution.

This has been fixed in [v3.8.1](https://github.com/patternfly/patternfly/releases/tag/v3.8.1). Please simply update your installation and let us know if you have any more trouble. 😄

**Comment by lroitman** [comment]
Thanks!! All set now!
