### ISSUE TITLE
In mobile mode, the Notification Drawer toggle is not accessible, drawer shouldn't expand

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-3#416]
There are 2 issues with the notification drawer in mobile mode.

1) You cannot get to the notification drawer toggle button as it is on the nav bar which is hidden
2) If the notification drawer is expanded, the left settings is too great and expanding the drawer makes it smaller. It should not be expandable in mobile mode.

**Comment by andresgalante** [comment]
Is this still a thing? I though we hide the notification drawer on mobile viewports.

Since we are working on mobile recommendations and we know the notification drawer is one of the problematic components, then I am going to close this issue and continue the this on the brother mobile discussion.

We will take in consideration the problems with notification drawer and mobile viewports for PF5.
