### ISSUE TITLE
navbar-toggle throw JS error in IE11 in fullscreen

### ISSUE THREAD

**Issue by gr0ebi** [patternfly/patternfly-3#457]
Hi,

I'm using patternfly since 2 days and rly like it with Visual Studio 2015 C# MVC.
Here is a screenshot of my error (in german): http://imgur.com/a/LHgXM
Line 1075 in patternfly.js
It says "Runtimeerror in Javascript: Object doesn't support this action"

I only get this error in Internet Explorer 11 when in full screen (not F11, normal fullscreen)

Thanks

**Comment by dlabrecq** [comment]
You may have discovered an IE 11 bug? Seems others are having similar problems with dispatchEvent on IE 11.

http://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11

**Comment by himdel** [comment]
This is also hitting ManageIQ, running on IE11, we get "Object doesn't support this action" both on the login screen and after that.

The code in question is

```
window.dispatchEvent(new Event('resize'))
```

in vertical navigation, `onResize`, same as @gr0ebi 's screenshot.

IE11 does not support this way of creating new events, the problem is not `dispatchEvent` but `new Event`.

Cc: @serenamarie125 (it already existed :))
