### ISSUE TITLE
Vertical navigation hides any horizontal navigation items on narrow viewports

### ISSUE THREAD

**Issue by rhwood** [patternfly/patternfly-3#496]
When the Vertical Navigation pattern is used with any menu items on the top navigation bar (status/alerts, help, user preferences/logout as shown at http://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html#_), and the viewport is narrow (such as on a smart phone, or Mozilla Firefox made narrow), the top navigation items are inaccessible.

**Comment by andresgalante** [comment]
@rhwood thanks, this is a known bug. Would you like to send a PR to fix it?
if not, @LHinson Can we create a story to deal with it?

**Comment by rhwood** [comment]
I won't be able to get to it anytime soon.

**Comment by andresgalante** [comment]
@rhwood Don't worry, we'll take care of it. Thanks for reporting the bug.

**Comment by rhamilto** [comment]
+1  This is a blocker for OpenShift.

cc:  @jwforres, @spadgett

**Comment by andresgalante** [comment]
@bleathem @LHinson let's work on this next sprint

**Comment by jwforres** [comment]
thanks @andresgalante ! Logout getting hidden at mobile is a non-starter :)

**Comment by LHinson** [comment]
We are going to be addressing this in this story here: https://patternfly.atlassian.net/browse/PTNFLY-1934

**Comment by andresgalante** [comment]
I've been looking into this bug for the past few days and although it seems simple, it isn't because of the how the DOM of the vertical nav is build.

I did find a solution by moving the left nav DOM to the top nav after the logo and using fancy CSS flexbox and positioning. This works but it requieres a lot of braking changes that I want to avoid.

On the other hand there is a simpler solution, but I wanted to run it with you guys before doing it. The goal is to move the links of the mast head to the bottom of the left nav following this spec:

https://github.com/jennyhaines/patternfly-design/blob/fb5be50ecd2f53c6d5b6ada04ce7a59d03178666/pattern-library/navigation/vertical-navigation/design/design.md

I can create a second instance of the masthead links after the vertical nav and hide it on large viewports.

Duplicating the navigation is far from ideal, but it'll allow us to fix the bug for this version of patternfly and introduce a flexible solution on the new version of patternfly with braking changes.

what do you guys think?

**Comment by rhamilto** [comment]
> I can create a second instance of the masthead links after the vertical nav and hide it on large viewports.

This is what we're doing today in OpenShift via a directive.  https://github.com/openshift/origin-web-console/blob/master/app/views/directives/header/_navbar-utility.html

**Comment by andresgalante** [comment]
@rhamilto that's good to know, we were planning to do the same for the pfang implementation.

Ok, I'll go on with that plan, thanks a lot for the patience and help
