### ISSUE TITLE
Card views do not appear to be keyboard-accessible (single + multi-select)

### ISSUE THREAD

**Issue by jawnsy** [patternfly/patternfly-3#529]
The examples for single- and multi-select card views do not appear to be keyboard accessible.  It's possible to add a `tabindex=0` to the card div to make it focusable, but I'm not quite sure how to make it behave nicely (I should note that I'm not an expert on the frontend - I just know enough to be dangerous :smile:)

Example here: http://www.patternfly.org/pattern-library/content-views/card-view
Full page view: http://www.patternfly.org/pattern-library/content-views/card-view/card-view-single-select.html

In the full-page view, you can highlight all of the controls in the toolbar nicely, but you're not able to make individual selections on items using the keyboard. This may cause problems when navigating with a screen reader.

**Comment by andresgalante** [comment]
@jawnsy sorry for the delay on this reply, and thanks for reporting the bug. Cards need a `tabindex`. Do you want to send a PR with the fix?

I've created a story to address it: https://patternfly.atlassian.net/browse/PTNFLY-2183

**Comment by andresgalante** [comment]
@jawnsy We've already fixed this on cards for pf5. I'll close this issue and track the progress of the fix for pf3/4 on the jira story.

also, check out the article we've wrote based on this: https://css-tricks.com/touch-devices-not-judged-size/

@LHinson this is something we should fix. Can we please prioritize it?
