### ISSUE TITLE
Dashboard widgets

### ISSUE THREAD

**Issue by xtrasmal** [patternfly/patternfly-3#57]
Hi there,

What are the libraries behind the dashboard graph? Right now they are just images, but I would like to implement these, so could you please tell me?

**Comment by rhamilto** [comment]
hi, @xtrasmal.  we're still working on implementing charts in patternfly and are hoping to finalize things over the next month. there is an experimental branch with the leading candidate charting library, c3.js, available at https://github.com/patternfly/patternfly/tree/c3 if you want to see the direction we're heading.  we're still planning some changes to the look and feel in this branch, and the radial progress meters will likely change or be eliminated (which is why they're still an image in https://rawgit.com/patternfly/patternfly/c3/tests/dashboard.html).  does that give you enough info to keep things moving?

**Comment by xtrasmal** [comment]
That is really amazing. Thank you very much. I've been looking at building the charts for the dashboard for 1,5 years at least :dancer:
