### ISSUE TITLE
sometime users just want to use handful widgets while npm install or bower install introduce huge assets

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-3#593]

**Comment by andresgalante** [comment]
True. A few years ago I've wrote how to do that with CSS
http://blog.andresgalante.com/howto/2015/03/06/patternfly-part-2.html

Material design is moving to that approach and frameworks like http://tachyons.io/ are already doing it.

Since breaking apart our monolotic aproach is such a huge task, we are doing it on the new version of patternfly:

https://github.com/patternfly/patternfly-css

@dabeng I'd love to review it with you, if we don't get a chance to do it before, let's take some time during the team meetup to sit and see it together 😄
