### ISSUE TITLE
Datatables pagination broken in Google Chrome

### ISSUE THREAD

**Issue by chrismueller** [patternfly/patternfly-3#616]
Hi. It seems that the datatables pagination is broken in Googles Chrome browser.
After changing the row count per page no items are being displayed and the rowcounts are change to "NaN-NaN".
Within Edge and Firefox everything works well. 
Even the demo on the patternfly homepage is affected: http://www.patternfly.org/pattern-library/content-views/table-view/#/code

![unbenannt](https://cloud.githubusercontent.com/assets/4072544/23814898/b847587e-05e5-11e7-80c9-5ce1039674fe.PNG)

**Comment by LHinson** [comment]
Thanks for reporting @chrismueller 

@dabeng, would you be able to look into this? Might make sense to look into #588 as well. Let me know and I'll create a story in Jira as well! Thanks :)

**Comment by andresgalante** [comment]
@LHinson @dabeng this might be a bug on the website, since the patternfly implementation works:

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view.html

If it is a bug on the website please move this issue to https://github.com/patternfly/patternfly-org

**Comment by pharasyte** [comment]
@dabeng @andresgalante 

I was able to replicate this my own project.

After digging into the issue, it seems that when 'Bootstrap Select' is initializing the pageSize, it adds the ".pagination-pf-pagesize" class to 'bootstrap-select' DIV that wraps the original SELECT element. This causes the onChange handler set in the "handlePageSize" function to fire twice, once for the original SELECT element, and once for the bootstrap-select DIV. When the handler tries to convert the value of the DIV to a number, it gets NaN. In my case, the handler for the DIV was being fired second, so I wound up with NaN.

I resolved this by setting the PAGE_SIZE_SELECTOR variable in "patternfly.dataTables.pfPagination.js" to ".bootstrap-select .pagination-pf-pagesize", so that the onChange event handler only attaches to the descendant SELECT element.

I still haven't found the difference between "https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view.html" and what I'm doing locally. Maybe some variance in dependency versions?

**Comment by dlabrecq** [comment]
Thanks for digging into this. I started looking at the dependency versions myself, but didn't expect bootstrap-select was duplicating the pagination-pf-pagesize selector elsewhere. I see the duplication on rawgit and on pf.org; although, rawgit appears to be working. We'll definitely want to fix this, regardless.

Would you like to submit your fix as a PR?

**Comment by pharasyte** [comment]
@dlabrecq Pull Request 617 submitted. 

I didn't test with any other browsers, though. Not sure if that makes a difference in this case.

**Comment by dlabrecq** [comment]
Using one or the other selector should be fine.

**Comment by iransamaneh** [comment]
this error is not exists only for chrome. i tested it with firefox and it is exists. Pull request 617 did not correct problem. i found error and i will correct it with a new pull request soon.
