### ISSUE TITLE
list-pf doesn't support disabled rows

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#676]
The new list-pf layout does not allow rows to be disabled. 

Currently the list view component from angular-patternfly shows disabled rows using .list-group-item.disabled (we inherit that from Bootstrap). However, there is no list-pf-item.disabled equivalent for use with the new list-pf layout.

In order to create a list component for patternfly-ng, we need to support disabled rows. I've added my own CSS to patternfly-ng for now, but the bootstrap disabled colors are too close to the new selected row (gray) highlighting.

**Comment by dlabrecq** [comment]
FYI, @andresgalante @LHinson

**Comment by LHinson** [comment]
@dlabrecq what is the use case for the disabled row? I ask because this is not something actually designed in PatternFly to date. Sounds like the product was able to leverage a bootstrap feature but should be looked at from a design perspective and added to our documentation for patternfly. 

We DO have an "unavailable" option which is denoted via text seen in the Table View but also applicable to List View. See http://www.patternfly.org/pattern-library/content-views/table-view/#/design I know "unavailable" and "disabled" are different but wanted to be sure that the use case is for a disabled row. 

Let me know the requirements so we can determine best next steps and get the appropriate stories added for pf design docs and development. 

Looping in @mcarrano @mgranfie @crobson

**Comment by dlabrecq** [comment]
I'm simply trying to achieve feature parity with the list view component in Angular Patternfly. You can see the disabled list view row example below -- select "Show Disabled Rows".

http://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfListView

Perhaps @dtaylor113 and/or @jeff-phillips-18 can shed some light regarding the disabled use cases for list view?

It was my understanding that everything in Angular Patternfly already had a pattern? Thus,  I assumed we would also bring those same features to patternfly-ng?

**Comment by LHinson** [comment]
This would be a case where an implementation does not have documentation. The design docs should be treated as the gold standard. 

I can work with @serenamarie125 @crobson @mcarrano @mgranfie to determine if this is a gap in our documentation and loop back around with re: whether or not it's needed for the ng implementation.

**Comment by dlabrecq** [comment]
Ok, please let me know. I can easily remove the disabled feature from the list component of patternfly-ng.
