### ISSUE TITLE
Toolbar Responsive Bug

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-3#698]
There appears to be an issue with the responsive state of the toolbar.

My example page is split into two panes, so the toolbar does not fill the entire window width. The left side of the page has a 200px wide navigation pane.

When the window is made smaller, the toolbar wraps, but there is no spacing between the rows. Only when the window is made extra small, does the layout show the correct row spacing.

I was able to reproduce this with the Patternfly test pages. I simply added two extra buttons to the toolbar example and padding-left: 200px.

**Small Window:**
![screen shot 2017-08-02 at 12 09 09 am](https://user-images.githubusercontent.com/17481322/28857963-2000da7a-771b-11e7-91ee-ca1718f7f17a.png)

**Extra Small Window:**
![screen shot 2017-08-02 at 12 39 02 am](https://user-images.githubusercontent.com/17481322/28857958-18142d4e-771b-11e7-9c32-ac49e57df6e9.png)

**Comment by dlabrecq** [comment]
Reported by @sjcox-rh

**Comment by andresgalante** [comment]
@LHinson Do we want to work on this for pf3?

**Comment by LHinson** [comment]
Unfortunately PF3 did not have a standard to adhere to for responsiveness therefore we have a mixed bag of components that are responsive and some that are not. We are making strides to ensure everything is responsive for our next major release. Given how old this issue is and I have not heard anything else on this issue, I'm going to close. Please feel free to re-open if there are concerns @dlabrecq @sjcox-rh
