### ISSUE TITLE
Label inside table CSS

### ISSUE THREAD

**Issue by strig** [patternfly/patternfly-3#81]
Labels inside of a table end up with very large text and unaligned with the table rows. 

![pfly](https://cloud.githubusercontent.com/assets/1923317/8513789/f42c09bc-2346-11e5-94a6-43c94052d776.PNG)

**Comment by rhamilto** [comment]
@strig, are you seeing this same behavior on the labels test page at https://rawgit.com/patternfly/patternfly/master/tests/labels.html?

**Comment by strig** [comment]
No, that looks right to me. Also, the table rows and font are larger somehow.

**Comment by rhamilto** [comment]
@strig, if https://rawgit.com/patternfly/patternfly/master/tests/labels.html looks right, there must be an issue in your implementation's markup or css.  The font inside the label may appear larger because of the font weight (600 or semi-bold), but it should be the same font size (12px) as the other text in the table.

**Comment by strig** [comment]
My bad, I was missing a doctype.

**Comment by rhamilto** [comment]
@strig, glad you figured it out.  :)
