### ISSUE TITLE
Resolve styling discrepancy between info status card examples

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-3#823]
Resolve styling discrepancy between the info status card examples. @jennyhaines provided some guidance and the team determined additional bottom margin should be added to this component.
@seanforyou23 created [this PR](https://github.com/patternfly/angular-patternfly/pull/668) in Angular, but as we discussed, this issue should be resolved in core so fixes will effect all repos. 

@seanforyou23 @jeff-phillips-18 let me know if I missed anything from our discussion.

**Comment by seanforyou23** [comment]
During the discussion there was mention of possibly splitting the difference between the top and bottom margin. So instead of having 16 or 20px bottom margin, we'd have 8 or 10px on both top and bottom margin.

Another possible enhancement to make [1] from a follow up discussion with @jennyhaines - could be to grow the top/bottom margin for the selector ".card-pf-info-status .card-pf-info-content" to 15px and reduce the top margin for the selector ".card-pf-info-status .card-pf-info-content .card-pf-title" down to 5px.

[1] may warrant a separate issue to be created, but wanted to mention since it came up in a follow-up discussion and relates to the general vertical rhythm of this component.

Hope this helps, let me know if I'm needed further.

**Comment by matthewcarleton** [comment]
@seanforyou23 can this be closed?
