### ISSUE TITLE
Fix SASS deprecation warning in patternfly sass support

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-3#852]
In Sass-preview branch currently, doing beta releases until we have acceptance.  There is a deprecation warning. New SASS versions will support percentage values in 0.xx form and the support for xx% will be dropped. I noticed that these are being used inconsistently and I think they should be unified.

@skateman @TheRealJon @jeff-phillips-18

**Comment by skateman** [comment]
Still reproducible in 3.37.0

**Comment by TheRealJon** [comment]
@dgutride @skateman Has this been fixed? I couldn't reproduce this issue now. Which sass compiler is throwing this warning (node or ruby)?

**Comment by skateman** [comment]
@TheRealJon can't test it right now, but my issues were with the ruby compiler in 3.37.

**Comment by TheRealJon** [comment]
Found that this is being caused by a bug in the conversion. For some reason, there are four instances of the fade function that are not being converted to rgba:

- [src/sass/converted/patternfly/_bootstrap-select.scss, line 71](https://github.com/patternfly/patternfly/blob/master/src/sass/converted/patternfly/_bootstrap-select.scss#L71)
- [src/sass/converted/patternfly/_bootstrap-select.scss, line 89](https://github.com/patternfly/patternfly/blob/master/src/sass/converted/patternfly/_bootstrap-select.scss#L89)
- [src/sass/converted/patternfly/_navbar.scss, line 196](https://github.com/patternfly/patternfly/blob/master/src/sass/converted/patternfly/_navbar.scss#L196)
- [src/sass/converted/patternfly/_navbar.scss, line 210](https://github.com/patternfly/patternfly/blob/master/src/sass/converted/patternfly/_navbar.scss#L210)

Sass does not have a native `fade` function, but our bootstrap-select dependency defines a `fade($color, $amount)` mixin, which uses the Sass rgba function similarly to the way we do our conversion.

I did notice that these are the only instances of the fade function that have the `!important` flag, so I'm checking the conversion pattern to ensure flags or comments are accounted for in this rule.
