### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by xeeljire** [patternfly/patternfly-3#901]
[This package](https://www.jsdelivr.com/package/npm/patternfly) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by cliffpyles** [comment]
@xeeljire Thanks for creating this ticket! What time are you typically online? I'd like to get a little clarification around the ticket?

**Comment by MartinKolarik** [comment]
@cliffpyles hi - jsDelivr team member here. Basically what the message means is that we don't know which file from your package is the one users should use. When you set a default file, we can show it at the top of the list, like [here](https://www.jsdelivr.com/package/npm/jquery). You'll also be able to use a shorter URL https://cdn.jsdelivr.net/npm/patternfly@3.37.4 instead of https://cdn.jsdelivr.net/npm/patternfly@3.37.4/dist/js/patternfly.min.js

#913 takes care of this.

**Comment by MartinKolarik** [comment]
Admittedly, this is not so useful when there are multiple files required to use the package.

**Comment by cliffpyles** [comment]
@MartinKolarik Thanks for the input! I think I am in agreement about the usefulness of the change with the current organization of the JS. The library is primarily for CSS and the JS is typically handled in external projects (with a few exceptions like you mentioned).

@xeeljire Since there isn't a single main JavaScript file that should be imported, would you mind providing some more context about what you are wanting to do?

**Comment by dgutride** [comment]
Closing due to lack of information - please reopen if there are any further details.
