### ISSUE TITLE
Inline edit example missing from core 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-3#967]
Related to pf-react issue: https://github.com/patternfly/patternfly-react/issues/187 which states: 

From @dabeng 
> I created a jquery version of [inline-edit in a form](https://rawgit.com/dabeng/patternfly/inline-edit2-dist/dist/tests/inline-edit.html) according to the [design doc](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#design) on pattern.org.

**Comment by jgiardino** [comment]
@dabeng You had included some comments in the [patternfly-react issue](https://github.com/patternfly/patternfly-react/issues/187#issuecomment-368381588). Would you mind adding them here for discussion?

@andresgalante @matthewcarleton @srambach If you have time, could you review the css and provide feedback?

**Comment by dabeng** [comment]
Maybe we can regard it as a starting point(**[inline edit in a form](https://rawgit.com/dabeng/patternfly/inline-edit2-dist/dist/tests/inline-edit.html)**) and go on with other inline-edit forms(inline-edit in a list view, table view) described in design doc.

**Inline Edit Additional Information:**
1. All the components used in "inline-edit in a form" are existing components listed in patrernfly library section of patternfly.org;

2. Currently, "inline-edit in a form" pattern includes 6 types of input field - enhanced text box, enhanced textarea, simple  single select of bootstrap select, multiple select of bootstrap select, bootstrap combobox, bootstrap datepicker;

3. <img width="18" alt="screen shot 2018-02-26 at 10 37 46 am" src="https://user-images.githubusercontent.com/5689075/36652248-90862612-1ae8-11e8-8b87-9774dcbce8f7.png"> spinner is used to mock async operations in common scenarios, e.g. submitting updated results via ajax after users complete their inline-edit;

4. IMO, "inline-edit in a form" shouldn't be entirely responsible for all sorts of form validation. In fact, form validation is complex enough to be a separate js library([Parsley](http://parsleyjs.org/) is a good example). Moreover, we have ["Errors and Validation"](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/) design already. Although not comprehensive and detailed, "Errors and Validation" is indispensable part of front-end development;

5. In "inline-edit in a form", there is only one field validation - <img width="18" alt="screen shot 2018-02-26 at 12 00 06 pm" src="https://user-images.githubusercontent.com/5689075/36652915-d46913b8-1aec-11e8-9b6d-3b6f8fa791c0.png"> save button will be enabled when user inputs the new value for a field;

6. Due to the following [code snippets](https://github.com/danielfarrell/bootstrap-combobox/blob/master/js/bootstrap-combobox.js#L424) of bootstrap combobox:
```js
, click: function (e) {
      e.stopPropagation();
      e.preventDefault();
      this.select();
      this.$element.focus();
    }
```
I can't capture the "click" event outside the combobox and then the save button can not be enabled when user selects the different dropdown menu item by click. Using arrow keys + Tab/Enter is OK;

7.  "inline-edit in a list view" is easy to implement, but "inline-edit in a table view" seems like a difficult task. For now, Datatables doesn't support inline row edit for now. There are some valuable references:
- [Inline row edit not working](https://datatables.net/forums/discussion/34765)
- [Inline table editing of a child row](https://datatables.net/forums/discussion/comment/125596/#Comment_125596)

8. We know that where is input, where is XSS. It will be a big bonus point if adding some anti-xss logic to input components or forms. The choice of anti-xss js libraries is not small. If you are interested in this field, I recommend you [jsxss](http://jsxss.com/en/index.html) 😊.

**Comment by jgiardino** [comment]
@dabeng Thanks for adding the notes! Would you also open a PR with the updates you made so that we can review from there?
