### ISSUE TITLE
icon button color

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-3#992]
When a button uses an icon instead of text, and displays without a button background, what color should that icon be? 

For example, if I were using an icon button without a button background, I would expect that I can implement this using:
`<button class="btn btn-link" type="button"><span class="pficon pficon-add-circle-o"></span></button>`

Which will result in a blue icon:
![image](https://user-images.githubusercontent.com/21063328/37619596-4b166d2c-2b90-11e8-8912-200634fcbfe5.png)

Are there other classes that can/should be applied to render an icon in a different color? For example, [the design documentation for Inline Edit in a Form](http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/#design) shows an Edit icon that is gray. But I don't see any examples of a gray icon button in our test pages.

@matthewcarleton @mcarrano @kybaker

**Comment by mcarrano** [comment]
This is an interesting question @jgiardino because we're just going through a process of changing the info (i) icon for infotips on form fields from blue to gray except upon hover. I think this is the way we thought about the edit icon. Having all of these blue created too much visual prominence. But I can see where it makes sense for a single add (+) icon like you show.

@cshinn just recently posted a design doc to better define actions. Chris, did you address this at all?

**Comment by LHinson** [comment]
I don't see this specifically addressed in the actions documentation. I also see a "create" action button in blue. @kybaker can you confirm what this is supposed to be so we can determine how to address.
